# Generated by Django 5.2.8 on 2025-11-28 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilCiudadano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colonia', models.CharField(blank=True, help_text='Colonia del usuario para alertas', max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('rango', models.CharField(choices=[('NOVATO', 'Novato (Solo reporta)'), ('GUARDIAN', 'Guardián (Sus reportes valen doble)'), ('MASTER', 'Máster (Validador oficial)')], default='NOVATO', max_length=20)),
                ('puntos_confianza', models.IntegerField(default=10, help_text='Puntos ganados por reportes verídicos')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
