# Generated by Django 5.2.8 on 2025-11-28 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_perfilciudadano'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='noticias/')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Noticia Oficial',
                'verbose_name_plural': 'Noticias Oficiales',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.AlterField(
            model_name='perfilciudadano',
            name='colonia',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='perfilciudadano',
            name='puntos_confianza',
            field=models.IntegerField(default=10),
        ),
    ]
