# Generated by Django 5.2.8 on 2025-11-28 03:40

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_noticia_alter_perfilciudadano_colonia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pozo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Pozo 3 - Los Héroes', max_length=100)),
                ('ubicacion', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('estado', models.CharField(choices=[('OPERATIVO', '🟢 Operando con normalidad'), ('MANTENIMIENTO', '🟡 En mantenimiento'), ('FALLA_BOMBA', '🔴 Falla en Bomba'), ('SIN_LUZ', '⚫ Sin Energía Eléctrica')], default='OPERATIVO', max_length=20)),
                ('profundidad', models.DecimalField(blank=True, decimal_places=2, help_text='Metros de profundidad', max_digits=6, null=True)),
                ('notas', models.TextField(blank=True, help_text='Detalles técnicos o bitácora rápida')),
            ],
            options={
                'verbose_name': 'Pozo de Agua',
                'verbose_name_plural': 'Pozos e Infraestructura',
            },
        ),
    ]
