# Generated by Django 5.0.14 on 2025-11-28 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_reporte_options_reporte_prioridad_and_more'),
        ('api', '0004_pozo'),
    ]

    operations = [
    ]
