# Generated by Django 5.0.14 on 2025-11-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_merge_20251128_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='foto_solucion',
            field=models.ImageField(blank=True, help_text='Evidencia de la reparación', null=True, upload_to='soluciones/'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='nota_seguimiento',
            field=models.TextField(blank=True, help_text='Mensaje oficial del gobierno al ciudadano'),
        ),
        migrations.AlterField(
            model_name='pozo',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pozo',
            name='notas',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pozo',
            name='profundidad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
