# Generated by Django 5.0.14 on 2025-11-28 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_reporte_foto_solucion_reporte_nota_seguimiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilciudadano',
            name='puntos_confianza',
        ),
        migrations.RemoveField(
            model_name='perfilciudadano',
            name='rango',
        ),
    ]
