# Generated by Django 5.0.14 on 2025-11-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_perfilciudadano_puntos_confianza_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporte',
            options={'ordering': ['-fecha_hora'], 'verbose_name': 'Solicitud ciudadana', 'verbose_name_plural': 'Ventanilla unica'},
        ),
        migrations.AddField(
            model_name='reporte',
            name='direccion_texto',
            field=models.CharField(blank=True, help_text='Calle y Número aproximado', max_length=255),
        ),
        migrations.AddField(
            model_name='reporte',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reporte',
            name='folio',
            field=models.CharField(editable=False, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='nota_seguimiento',
            field=models.TextField(blank=True, help_text='Respuesta oficial del funcionario'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='status',
            field=models.CharField(choices=[('PENDIENTE', 'Recibido / Pendiente'), ('ASIGNADO', 'Asignado a Cuadrilla'), ('EN_PROCESO', 'En Reparación'), ('RESUELTO', 'Concluido'), ('CANCELADO', 'Improcedente')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='tipo_problema',
            field=models.CharField(choices=[('FUGA', 'Fuga de Agua'), ('ESCASEZ', 'Escasez / No hay agua'), ('CALIDAD', 'Mala Calidad / Agua Sucia'), ('ALCANTARILLADO', 'Falla en Drenaje/Alcantarilla'), ('TRAMITE', 'Solicitud de Trámite')], max_length=20),
        ),
    ]
