# Generated by Django 5.0.14 on 2025-11-28 11:42

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_reporte_options_reporte_direccion_texto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pipa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_economico', models.CharField(help_text='Ej. PIPA-04', max_length=50, unique=True)),
                ('capacidad_litros', models.IntegerField(default=10000)),
                ('chofer', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(choices=[('DISPONIBLE', '🟢 Disponible'), ('EN_RUTA', '🚚 En Ruta / Trabajando'), ('TALLER', '🔴 En Mantenimiento')], default='DISPONIBLE', max_length=20)),
                ('ubicacion_actual', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
        ),
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ['-fecha_publicacion']},
        ),
        migrations.AlterModelOptions(
            name='pozo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='validacion',
            options={},
        ),
        migrations.AlterField(
            model_name='pozo',
            name='estado',
            field=models.CharField(default='OPERATIVO', max_length=20),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='direccion_texto',
            field=models.CharField(blank=True, help_text='Calle y Número', max_length=255),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='foto_solucion',
            field=models.ImageField(blank=True, null=True, upload_to='soluciones/'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='nota_seguimiento',
            field=models.TextField(blank=True, help_text='Respuesta oficial'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='prioridad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='validaciones',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reporte',
            name='pipa_asignada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios', to='api.pipa'),
        ),
    ]
