# Generated by Django 5.0.14 on 2025-11-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_pipa_alter_noticia_options_alter_pozo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='folio',
            field=models.CharField(editable=False, max_length=20, null=True, unique=True),
        ),
    ]
